### ISSUE TITLE
授权回来后,我这里怎么有两个code和state,求大佬看一下?

### ISSUE THREAD

**Issue by rsning** [sunniejs/vue-wechat-auth#4]
http://localhost:9018/#/?code=0813uU9y1GRINb0g56by1BYI9y13uU9X&code=061BXU7i0z4C7u1kRi7i0NvV7i0BXU7e&state=ij95fj80v1g68je4t4kki&state=d7q3yd8v9bbd5cgkelvb8

**Comment by rsning** [comment]
11

**Comment by tlerbao** [comment]
@rsning 兄弟我也有两个甚至三个code 是什么原因导致的呢》
